version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: docker
      POSTGRES_DB: crm
      POSTGRES_PASSWORD: 4eebua2m

  adminer:
    image: adminer
    restart: always
    ports:
      - 5432:5432
  volumes:
    - polls_pg_data:/postgres

volumes:
  polls_pg_data:
